language: java # to trigger the build on a 'jvm-otp' travis worker
env:
  - PLAY_VERSION=2.1.0
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
  - set SBT_OPTS= -Xms256m Xmx52m -XX:MaxPermSize=512m
script: play-${PLAY_VERSION}/play test
