language: java # to trigger the build on a 'jvm-otp' travis worker
env:
  - PLAY_VERSION=2.0.2
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
